Repository MAVRICK-1/EduWeb, pull requests merged in 2024-05, with the labels that each got.

#9 Added contributors list
  README.md
Labels: gssoc, level1

#10 Added valid content to the website
  index.html
Labels: gssoc, level1

#23 added workflows
  .github/workflows/autocomment-issue.yml
  .github/workflows/autocomment-pr-merge.yml
  .github/workflows/autocomment-pr-raise.yml
Labels: gssoc, level2

#24 added the remaining workflows
  .github/workflows/autocomment-iss-close.yml
  .github/workflows/close-old-issue.yml
  .github/workflows/close-old-pr.yml
Labels: gssoc, level2

#14 Added pull_request_template.md
  pull_request_template.md
Labels: gssoc, level1

#31 added the git hub logo
  index.html
Labels: gssoc, level2

#32 [FEAT]: Created Issue forms and made the issue options more visually appealing
  .github/ISSUES_TEMPLATE/bug_report.md
  .github/ISSUES_TEMPLATE/documentation.md
  .github/ISSUES_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/documentation_update.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: gssoc, level2

#29 added the workflow as mentioned in #28
  .github/workflows/close-on-merge.yml
Labels: gssoc, level1

#30 Fixes: #12 Add enhanced_readme
  CONTRIBUTING.md
  README.md
Labels: gssoc, level1

#36 Updated CONTRIBUTING.md
  CONTRIBUTING.md
Labels: gssoc, level1

#37 Added contact form
  assets/css/style.css
  assets/images/contact.svg
  assets/js/script.js
  index.html
Labels: gssoc, level3

#38 Icon in footer hide content of that footer
  assets/css/style.css
Labels: gssoc, level1

#40 Year needs to update dynamic in footer
  index.html
Labels: gssoc, level1
