Repository MAVRICK-1/EduWeb, pull requests merged in 2024-06, with the labels that each got.

#46 Improve course and news section
  index.html
Labels: gssoc, level2

#44 login page created
  .vscode/settings.json
  Login/avatar.svg
  Login/index1.html
  Login/script1.js
  Login/script2.js
  Login/signup.html
  Login/styles.css
  README.md
  assets/css/style.css
  assets/js/script.js
  index.html
Labels: gssoc, level3

#58 Added link to contact button on navbar
  index.html
Labels: gssoc

#53 Added FAQ section
  assets/css/style.css
  assets/js/accordian.js
  assets/js/script.js
  index.html
Labels: gssoc, level2

#60 Add new hover effect on buttons
  assets/css/style.css
  index.html
Labels: gssoc, level1

#59 Add location, email and contact icon and icon-hover at footer section
  index.html
Labels: gssoc, level1

#65 Routed links in the Footer section
  README.md
  index.html
Labels: gssoc, level1

#67 update courses link and some other links
  index.html
Labels: gssoc

#52 there is search button at top but no input field to take user input #35
  assets/css/style.css
  assets/js/script.js
  index.html
Labels: gssoc, level1

#71 Corrected the spelling from thse to these in README file
  README.md
Labels: gssoc

#72 Typo fix
  index.html
Labels: gssoc

#74 I have added content to it please go through it.
  index.html
Labels: gssoc, level1

#79 "Categories" Grid-List Hover Effect Added
  assets/css/style.css
Labels: gssoc, level1
